language: node_js
cache:
  directories: 
    - $HOME/server/node_modules
    - $HOME/client/node_modules
    - $HOME/travis/.cache

before_install:
  - sudo apt-get install -y netcat
  - ls -l $TRAVIS_BUILD_DIR/scripts
node_js:
  - 10
script:
  - chmod ugo+x $TRAVIS_BUILD_DIR/scripts/wait_for_service.sh
  # install dependencies
  - cd "$TRAVIS_BUILD_DIR"/server && yarn
  - cd "$TRAVIS_BUILD_DIR"/client && yarn
  # run things
  #- cd "$TRAVIS_BUILD_DIR"/server && yarn && yarn lint && yarn test:coveralls && yarn cucumber
  - cd "$TRAVIS_BUILD_DIR"/server && yarn start &
  - cd SKIP_PREFLIGHT_CHECK=true "$TRAVIS_BUILD_DIR"/client && yarn start &
  - $TRAVIS_BUILD_DIR/scripts/wait_for_service.sh localhost 3000 && $TRAVIS_BUILD_DIR/scripts/wait_for_service.sh localhost 8000 # wait for things
  - cd "$TRAVIS_BUILD_DIR/client" && yarn wdio # run selenium
  - kill %1 %2 # kill things