language: node_js
node_js:
  - 10
addons:
  chrome: stable
before_install:
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
 - cd client && yarn --network-concurrency 1 && nohup bash -c 'yarn start' &
script:
 - cd client && yarn --network-concurrency 1 && yarn wdio && cd ../server && yarn --network-concurrency 1 && yarn lint && yarn test:coveralls && yarn cucumber
