language: node_js
node_js:
  - 10
addons:
  chrome: stable
before_script:
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
 - cd client && yarn && nohup bash -c 'yarn start' &
script:
 - cd client && yarn && yarn wdio && cd ../server && yarn && yarn lint && yarn test:coveralls && yarn cucumber
